INSERT INTO `accounts_viewcars` VALUES (1, 'Hyundai i10', 'SERIES II S 4x4', '2003', '2.5L', 'DIESEL TURBO F/INJ\r\n', '88.5L', '83Kw', '4 Seats', '4D WAGON', 'Automatic', 'images/Hyundai-i10.png');
INSERT INTO `accounts_viewcars` VALUES (2, 'Kia Picanto', 'SERIES II SE 4x4', '2004', '4.0L', 'MULTI POINT F/INJ\r\n', '93L', '136Kw', '4 Seats', '4D WAGON', 'Automatic', 'images/kia-picanto.png');
INSERT INTO `accounts_viewcars` VALUES (5, 'Mitsubishi Lancer', 'Tdi 4x4', '1996', '2.5L', 'DIESEL TURBO', '88.5L', '83Kw', '4 Seats', '4D WAGON', 'Automatic', 'images/mitsubishi-lancer.png');
INSERT INTO `accounts_viewcars` VALUES (6, 'Kia Rio', 'ES V8 4x4', '1999', '4.0L', 'MULTI POINT F/INJ', '95L', '132Kw', '5 Seats', '4D WAGON', 'Automatic/Standard', 'images/kia-rio.png');
INSERT INTO `accounts_viewcars` VALUES (7, 'Hyundai Accent', 'SERIES II SE 4x4', '2004', '4.0L', 'MULTI POINT F/INJ', '93L', '136Kw', '5 Seats', '4D WAGON', 'Automatic/Standard', 'images/hyundai-accent.png');
INSERT INTO `accounts_viewcars` VALUES (8, 'Kia Cerato', 'SERIES II S 4x4', '2003', '4.0L', 'MULTI POINT F/INJ', '93L', '136Kw', '5 Seats', '4D WAGON', 'Automatic/Standard', 'images/kia-cerato.png');
INSERT INTO `accounts_viewcars` VALUES (9, 'Suzuki APV', 'S 4x4', '1998', '2.5L', 'DIESEL TURBO', '88.5L', '83Kw', '7 Seats', '4D WAGON', 'Standard', 'images/suzuki-apv.png');
INSERT INTO `accounts_viewcars` VALUES (10, 'Mitsubishi Sportero', 'XEi 4x4', '2000', '1.8L', 'MULTI POINT F/INJ', '59L', '84Kw', '4 Seats', '3D HARDBACK', 'Automatic', 'images/mitsubishi-sportero.png');
INSERT INTO `accounts_viewcars` VALUES (11, 'Kia Sorento', 'ES V8 4x4', '1999', '4.0L', 'MULTI POINT F/INJ', '95L', '132Kw', '5 Seats', '4D WAGON', 'Automatic', 'images/kia-sorento.png');
INSERT INTO `accounts_viewcars` VALUES (12, 'Kia Sportage', 'Tdi 4x4', '1994', '2.5L', 'DIESEL TURBO', '88.5L', '83Kw', '5 Seats', '4D WAGON', 'Automatic', 'images/kia-sportage.png');
INSERT INTO `accounts_viewcars` VALUES (13, 'Kia Sorento', 'SERIES II SE 4x4', '2004', '4.0L', 'MULTI POINT F/INJ', '93L', '136Kw', '4 Seats', '4D WAGON', 'Automatic', 'images/kia-picanto.png');
INSERT INTO `accounts_viewcars` VALUES (14, 'Toyota Hiace', 'SERIES II S 4x4', '2003', '4.0L', 'MULTI POINT F/INJ', '93L', '136Kw', '9 Seats', '4D WAGON', 'Standard', 'images/toyota-hiace.png');
INSERT INTO `accounts_viewcars` VALUES (15, 'Audi Q2', '1.8 TURBO', '2004', '1.8L', 'TURBO MPFI', '55L', '110Kw', '5 Seats', '5D HATCHBACK', 'Automatic', 'images/Q2.jpg');
INSERT INTO `accounts_viewcars` VALUES (16, 'Audi Q5', 'B6 2.0 AVANT', '2003', '2.0L', 'MULTI POINT F/INJ', '70L', '184Kw', '5 Seats', '4D WAGON', 'Automatic', 'images/Q5.jpg');
INSERT INTO `accounts_viewcars` VALUES (17, 'Audi Q7', 'C5', '2001', '2.7L', 'TWIN TURBO MPFI', '70L', '184Kw', '7 Seats', '5D HATCHBACK', 'Automatic/Standard', 'images/Q7.jpg');
INSERT INTO `accounts_viewcars` VALUES (18, 'Audi A4', '1.8 TURBO', '2004', '1.8L', 'TURBO MPFI', '55L', '110Kw', '5 Seats', '3D HATCHBACK', 'Automatic', 'images/A4.jpg');
INSERT INTO `accounts_viewcars` VALUES (19, 'Audi R8', 'C5', '2001', '2.7L', 'TWIN TURBO MPFI', '70L', '214Kw', '2 Seats', '4D WAGON', 'Automatic/Standard', 'images/R8.jpg');
INSERT INTO `accounts_viewcars` VALUES (20, 'Toyota C-HR', 'E53 3.0i', '2004', '3.0L', 'MULTI POINT F/INJ', '93L', '170Kw', '7 Seats', '4D WAGON', 'Automatic', 'images/3559_BR01xyo.png');
INSERT INTO `accounts_viewcars` VALUES (21, 'Mitsubishi Eclipse', 'S15 SX SPEC S', '2001', '2.0L', 'TURBO MPFI', '65L', '147Kw', '7 Seats', '4D HATCHBACK', '4D HATCHBACK', 'images/ZEAUCGAR999.jpg');
INSERT INTO `accounts_viewcars` VALUES (22, 'Toyota Kluger', 'SX SPORTS LIMITED', '1998', '2.0L', 'TURBO MPFI', '65L', '147Kw', '5 Seats', '2D COUPE', 'Automatic/Standard', 'images/ZEAUFFAR999.jpg');
INSERT INTO `accounts_viewcars` VALUES (23, 'Mitsubishi Pajero Sport GLX', 'Mi16', '2000', '2.0L', 'MULTI POINT F/INJ', '60L', '100Kw', '5 Seats', '5D HATCHBACK', 'Automatic/Standard', 'images/ZEAUSFAR999.jpg');
INSERT INTO `accounts_viewcars` VALUES (24, 'Mitsubishi MIRAGE HATCH', 'PROTEGE', '2006', '1.6L', 'MULTI POINT F/INJ', '55L', '78Kw', '4 Seats', '4D SEDAN', 'Automatic', 'images/Mirage18-Hero-001_djm7dOr.png');
INSERT INTO `accounts_viewcars` VALUES (25, 'Toyota GTS 86', 'MY06 CLASSIC', '2005', '2.4L', 'MULTI POINT F/INJ', '57L', '317Kw', '2 Seats', '4D SEDAN', 'Automatic', 'images/ToyotaAccess_86.jpg');
INSERT INTO `accounts_viewcars` VALUES (26, 'Toyota Prius c', 'ASTINA SHADES', '2000', '1.6L', 'MULTI POINT F/INJ', '55L', '78Kw', '4 Seats', '5D HATCHBACK', 'Automatic/Standard', 'images/ToyotaAccess_prius_c_Z1ng6GI.jpg');
