# Generated by Django 2.1.1 on 2018-09-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_ID', models.TextField()),
                ('Customer_Name', models.TextField()),
                ('Order_ID', models.TextField()),
                ('Order_CreateDate', models.TextField()),
                ('Order_PickupDate', models.TextField()),
                ('Order_Pickup_Store', models.TextField()),
                ('Pickup_Store_Name', models.TextField()),
                ('Order_ReturnDate', models.TextField()),
                ('Order_ReturnStore', models.TextField()),
                ('Return_Store_Name', models.TextField()),
                ('Car_ID', models.TextField()),
                ('Car_MakeName', models.TextField()),
                ('Car_Model', models.TextField()),
                ('Car_Series', models.TextField()),
                ('Car_SeriesYear', models.TextField()),
            ],
        ),
    ]
